"""Small compatibility guardrail, not a general PostgreSQL safety analyzer."""
import argparse
import io
import re
import sys
from pathlib import Path

import sqlparse
from sqlparse import tokens as T


def words(sql: str) -> list[str]:
    result = []
    for kind, value in sqlparse.lexer.tokenize(sql):
        if kind in T.Comment or kind in T.Whitespace:
            continue
        if value.startswith("$"):
            delimiter = re.match(r"\$(?:[A-Za-z_][A-Za-z_0-9]*)?\$", value)
            if delimiter and value.endswith(delimiter[0]):
                # Inspect static statements inside DO/function bodies too.
                result.extend([";", *words(value[len(delimiter[0]):-len(delimiter[0])]), ";"])
                continue
        if kind in T.Literal.String or value.startswith('"'):
            result.append("<literal>")
            continue
        result.extend(re.findall(r"[A-Za-z_][A-Za-z_0-9]*|[;(),.]", value.upper()))
    return result


def violations(sql: str) -> list[str]:
    found = set()
    tokens = words(sql)
    for i, token in enumerate(tokens):
        following = tokens[i + 1] if i + 1 < len(tokens) else ""
        if token == "DROP" and following in ("COLUMN", "TABLE"):
            found.add(f"DROP {following} is not allowed during compatibility migrations.")
        if token == "TRUNCATE":
            found.add("TRUNCATE is not allowed during compatibility migrations.")
        if token == "ALTER" and following == "TABLE":
            end = next((j for j in range(i + 2, len(tokens)) if tokens[j] == ";"), len(tokens))
            clause = tokens[i + 2:end]
            if "DROP" in clause:
                found.add("ALTER TABLE ... DROP is not allowed during compatibility migrations.")
            if "RENAME" in clause:
                found.add("ALTER TABLE ... RENAME is not allowed during compatibility migrations.")
        if token == "EXECUTE" and following not in ("FUNCTION", "PROCEDURE"):
            found.add("Dynamic EXECUTE cannot be verified by this compatibility checker.")
    return sorted(found)


def compatibility_sql() -> str:
    from alembic import command
    from api.migration_runner import alembic_config

    output = io.StringIO()
    config = alembic_config()
    config.output_buffer = output
    command.upgrade(config, "001:003", sql=True)
    return output.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--generate", action="store_true", help="Check SQL generated by Alembic for revisions 002 and 003.")
    source.add_argument("--file", type=Path, help="Check an existing SQL file.")
    args = parser.parse_args()
    sql = compatibility_sql() if args.generate else args.file.read_text()
    problems = violations(sql)
    if problems:
        print("Dangerous migration detected:", file=sys.stderr)
        for problem in problems:
            print(f"- {problem}", file=sys.stderr)
        return 1
    print("Compatibility SQL passed the configured safety checks.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

